services:
  train:
    depends_on:
      - postgres
      - mlflow
    working_dir: /app
    command: python -m london_housing_ai.train_main --config src/london_housing_ai/configs/config_dataset2.yaml --csv src/london_housing_ai/data/Property_Prices_2024.csv
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./mlruns:/mlruns
      - ./credentials:/app/credentials
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-dbuser}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-postgres}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/app/credentials/service-account.json}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      MLFLOW_ARTIFACT_URI: ${MLFLOW_ARTIFACT_URI:-file:/mlruns}
      MLFLOW_ARTIFACT_PATH: ${MLFLOW_ARTIFACT_PATH:-catboost_model}
      MLFLOW_MODEL_NAME: ${MLFLOW_MODEL_NAME:-london_housing_model}
      DEV_MODE: ${DEV_MODE:-false}

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME:-dbuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    depends_on:
      - postgres
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials/service-account.json
    ports:
      - "5000:5000"
    volumes:
      - ./credentials:/app/credentials
      - ./mlruns:/mlruns
    command: >
      mlflow server
        --backend-store-uri postgresql://${DB_USERNAME:-dbuser}:${DB_PASSWORD:-password}@postgres:${DB_PORT:-5432}/${DB_NAME:-postgres}
        --default-artifact-root ${MLFLOW_ARTIFACT_URI:-file:/mlruns}
        --host 0.0.0.0
        --port 5000

  api:
    build: .
    working_dir: /app
    command: uvicorn london_housing_ai.api.main_api:app --host 0.0.0.0 --port 7777 --reload
    depends_on:
      - mlflow
    ports:
      - "7777:7777"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_MODEL_NAME: ${MLFLOW_MODEL_NAME:-london_housing_model}
      MLFLOW_ARTIFACT_PATH: ${MLFLOW_ARTIFACT_PATH:-catboost_model}
      PYTHONPATH: /app/src
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./mlruns:/mlruns

volumes:
  pgdata:
